# Generated by Django 3.1.1 on 2020-09-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200918_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='reply',
        ),
    ]
