# Generated by Django 3.1.1 on 2020-11-16 17:18

from django.db import migrations, models
import market.commons.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=market.commons.file_upload.get_upload_path),
        ),
    ]
